name: open-games-hs
version: '0.1.0.0'
synopsis: Haskell implementation of open games
category: Math
author: Jules Hedges, André Videla, Philipp Zahn & other contributors
maintainer: philipp.zahn@protonmail
copyright: Jules Hedges, André Videla, Philipp Zahn & other contributors
license: AGPL
extra-source-files:
- README.md


library:
  source-dirs: src
  exposed-modules:
    # - OpenGames.Engine.AtomicGames
    - OpenGames.Engine.BayesianGames
    - OpenGames.Engine.Diagnostics
    - OpenGames.Engine.Engine
    - OpenGames.Engine.OpenGames
    - OpenGames.Engine.OpticClass
    - OpenGames.Engine.TLL
    - OpenGames.Preprocessor
    - OpenGames.Preprocessor.BlockSyntax
    - OpenGames.Preprocessor.Codegen
    - OpenGames.Preprocessor.CompileBlock
    - OpenGames.Preprocessor.CompileSyntax
    - OpenGames.Preprocessor.Parser
    - OpenGames.Preprocessor.RuntimeAST
    - Examples.SimultaneousMoves
    - Examples.Bayesian
    - Examples.Decision
    - Examples.SequentialMoves
    - Examples.Auctions.AuctionSupportFunctions
    - Examples.Auctions.ChooseReservePrice
    - Examples.Auctions.DutchAuction
    - Examples.Auctions.SequentialAuction
    - Examples.Auctions.SimultaneousBidAuction
    - Examples.Markov.RepeatedPD
    - Examples.Markov.RepeatedPDNonState
    - Examples.Markov.TwoStageMarkov
    - Examples.Markov.TestSimpleMonteCarlo
    - Examples.Markov.TestSimpleMonteCarlo.Continuation
    - Graphics

dependencies:
    - base >=4.7 && <5
    - act
    - mtl
    - ghc
    - transformers
    - probability
    - ad
    - poly
    - profunctors
    - template-haskell
    - parsec
    - QuickCheck
    - comonad
    - haskeline
    - hashmap
    - hashable
    - extra
    - fgl
    - graphviz
    - lens
    - typed-process
    - mwc-random
    - random
    - vector
    - monad-bayes
    - criterion


executables:
  open-games-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - open-games-hs
  act-exec:
    main:                Main.hs
    source-dirs:         act
    ghc-options:
      - -fwarn-unused-imports
    dependencies:
      - act >= 0.1 && < 1
      - open-games-hs
      - file-embed
      - bytestring
      - validation
      - hevm
      - containers
  graphics:
    main:                Main.hs
    source-dirs:         graphics
    dependencies:
      - open-games-hs
      - graphviz
      - template-haskell
      - criterion
